### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ncoden** [sindresorhus/gulp-zip#102]
Hi,

It would be useful to get the list of changes and bugfixes between versions, with migrations notes or recommendations if any. For now we have to check in the code if any change in the API was made, and it can take some time when you have a lot of dependencies to update.

Please provide a `CHANGELOG.md` file or GitHub releases.

Thank you.

**Comment by sindresorhus** [comment]
The changelog is just the commit history: https://github.com/sindresorhus/gulp-zip/commits/master
