### ISSUE TITLE
Feature Request: support Yazl's `options.mtime` to enable creating byte-for-byte identical zip archives across rebuilds

### ISSUE THREAD

**Issue by robertbullen** [sindresorhus/gulp-zip#103]
As it works today, individual file modification timestamps are placed as metadata inside the resulting zip file. If for any reason the files that go into the zip file are "touched" such that their timestamp metadata change, but not their contents, the resulting zip file will be different.

This is bad for detecting whether the contents of the files within the zip have actually changed. For example, some cloud deployment technologies support the concept of a zip file hash when deploying to AWS Lambda. If the hash changes, then the code is redeployed. If the hash is the same, the code needn't be redeployed.

This feature could be easily added to gulp-zip by simply supporting and propagating Yazl's `options.mtime` property. If clients of gulp-zip supply a value for this option, then it will override the system's timestamp for all files in the zip, and the resulting zip will have a consistent hash across code rebuilds when the source code doesn't change.

This feature would be opt-in only and full backwards compatibility can be preserved.

**Comment by sindresorhus** [comment]
Valid use-case. PR welcome :)

**Comment by robertbullen** [comment]
Ask and ye shall receive!
