### ISSUE TITLE
yazl 2.5.0 broke gulp-zip

### ISSUE THREAD

**Issue by chadn** [sindresorhus/gulp-zip#109]
gulp-zip became unusable for us a few days ago due to bug in ver 2.5.0 of yazl, for details see
https://github.com/thejoshwolfe/yazl/issues/47

In the meantime, the workaround is to use my fork of v4.2.0 which hardcodes to use yazl 2.4.3 
[chadn/gulp-zip/commit/cc7515e](https://github.com/chadn/gulp-zip/commit/cc7515e)

**Comment by sindresorhus** [comment]
Closing as this was fixed.
