### ISSUE TITLE
How to use the options configuration object

### ISSUE THREAD

**Issue by gubbigubbi** [sindresorhus/gulp-zip#110]
Awesome gulp plugin! Could we add some examples of using the options object? I am happy to do a PR and update the documentation but I cant quite figure it out, for example the following doesnt seem to work:

```
.pipe(
			zip( 'kona-instagram-for-gutenberg.zip', {
				allowEmpty: true,
			} )
		)
		.pipe( gulp.dest( './' ) )
```

**Comment by sindresorhus** [comment]
There's no `allowEmpty` option. The supported options are documented in the readme. As for the docs, I think it's already clear enough how to use the options.
