### ISSUE TITLE
Can't install w/ npm

### ISSUE THREAD

**Issue by parkerdyer** [sindresorhus/gulp-zip#113]
I've tried running the npm install command a few times and get this error. My logs don't show any more helpful information. Not sure if other users have encountered this issue. 

node: v.10.15.1
npm: v.6.4.1

```npm install --save-dev gulp-zip
npm ERR! Unexpected token } in JSON at position 271151 while parsing near '...vWRSCyZU=",
npm ERR!         }
npm ERR!       }
npm ERR!     },
npm ERR!    ...'```

**Comment by sindresorhus** [comment]
Use https://npm.community/ for npm support.
