### ISSUE TITLE
Remove gulp peer dependency?

### ISSUE THREAD

**Issue by spalger** [sindresorhus/gulp-zip#114]
We're using gulp-zip directly with vinyl-fs (without gulp) and would like to remove the warning when installing dependencies caused by the listed gulp peer dependency. It seems this library doesn't actually have a dependency on gulp, and seems like maybe we could just remove it. Thoughts?

**Comment by sindresorhus** [comment]
It's using `peerDependencies` to indicate that it won't work with Gulp 3. How about I make it optional using `peerDependenciesMeta`?

https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md (It's implemented in Yarn and npm)

**Comment by spalger** [comment]
Sounds good to me!

**Comment by spalger** [comment]
PR incoming
