### ISSUE TITLE
Files without name are ignored during zip (e.g. ".txt")

### ISSUE THREAD

**Issue by AndreasThumfart** [sindresorhus/gulp-zip#116]
As the title says, files which only have and ending, but no actual name, like .txt, .xml or .config are ignored during packaging.

Error is reproducable the following way:
File structure:
Folder "test"
with two files: ".txt" and "test.txt"

Command used:
gulp.src("./test/**")
    .pipe(zip("test.zip"))
    .pipe(gulp.dest("."))

Zip file "test.zip" including the file "test.txt" is created. File ".txt" is missing.

**Comment by sindresorhus** [comment]
You want the `dot` option: https://gulpjs.com/docs/en/api/src

**Comment by AndreasThumfart** [comment]
Thanks, that solves my problem!
