### ISSUE TITLE
Request: Add more examples to documentation

### ISSUE THREAD

**Issue by SamuelMiller** [sindresorhus/gulp-zip#122]
Hello, as a novice to Gulp, from the gulp-zip documentation I am not clear on how to use the options. Please provide examples in the documentation, particularly the modifiedTime option, which I assume adds a timestamp to the output file name.

**Comment by sindresorhus** [comment]
This is not the place to document Gulp conventions. See the Gulp docs on how to use Gulp.

**Comment by sindresorhus** [comment]
> which I assume adds a timestamp to the output file 

I'm not sure why you would assume that since the docs clearly says what it does:

> Overrides the modification timestamp for all files added to the archive.

**Comment by SamuelMiller** [comment]
I am speaking about your plugin.  Keep in mind, that there are many people like me who are novices who learn by examples.

This plugin, for example, provides a few examples of the various options. https://www.npmjs.com/package/gulp-useref. 

In the documentation of Gulp Zip, it states:
```
modifiedTime

Type: Date
Default: undefined

Overrides the modification timestamp for all files added to the archive.

Tip: Setting it to the same value across executions enables you to create stable archives that change only when the contents of their entries change, regardless of whether those entries were "touched" or regenerated.
```
What would be the format of the "date"?

For example, in my project, I have

```
function zipProject() {
    return src(paths.zip.src)
        .pipe(zip(`samba_project_${(new Date().toJSON().slice(0, 10))}.zip`))
        .pipe(dest(paths.zip.dest));
};
```

How, would I define the "modifiedTime" option. I've added a little datestamp JS snippet I found on the web to append the date on the file name.  Thanks. By the way, great plugin.
