### ISSUE TITLE
import zip from 'gulp-zip' not working!?

### ISSUE THREAD

**Issue by blaasvaer** [sindresorhus/gulp-zip#125]
import zip from 'gulp-zip';
^^^^^^

SyntaxError: Cannot use import statement outside a module

I'm using this at the top of my gulpfile.js.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by blaasvaer** [comment]
Problem is my main in package.json is not pointing to your specific module, I'm pointing to 'index.js' which is my entrypoint. I don't know why one would expect the use of this module in this way by default.

**Comment by blaasvaer** [comment]
I down graded to v5 and can now use require and get on with my life.
