### ISSUE TITLE
How can I zip files including parent directory?

### ISSUE THREAD

**Issue by Ann-Dederkal** [sindresorhus/gulp-zip#23]
I have folders structure:

```
| build
    |_irep
        |_name1
            |_file1
            |_file2
        |_name2
            |_file3
            |_file4
```

I need to zip each folder in directory build/irep including directory in name1, name2 in zips
So as a result I should have two zip files like this:

```
name1.zip
    |_name1
        |_file1
        |_file2
```

I've found a solution using rename plugin and changing directory but I guess there is better solution (probably using cwd), but I could not find it.

My task:

```
gulp.src('build/irep/' + fullName + '/**')
    .pipe(rename(function (path) {
        path.dirname = fullName + '/' + path.dirname;
    }))
    .pipe(zip(fullName + '.zip'))
    .pipe(gulp.dest('build/irep'));
```

**Comment by rudyarchitect** [comment]
> Thank you. I saw this issue and tried to do smth like this:
> 
> ```
> gulp.src('**', {cwd: path.join(process.cwd(), '/build/irep/')})
>     .pipe(zip(fullName + '.zip'))
>     .pipe(gulp.dest('build/irep'));
> ```
> 
> But I got a package without parent directory inside:
> 
> ```
> name1.zip
>     |_file1
>     |_file2
> ```

I also have this problem and I agree with @palamccc 's solution. but if you want add a parent directory, please add {base:'irep/'} in your example, I checked it's work.

**Comment by mariovalney** [comment]
You can use [gulp-rename](https://github.com/hparra/gulp-rename) to add a "parent" directory:

```
gulp.src(your_files)
    .pipe(
      rename(
        function(path) {
          path.dirname = 'parent-diretory/' + path.dirname;
        }
      )
    )
    .pipe(zip('your-zip-file.zip'))
    .pipe(gulp.dest('.'));
```
