### ISSUE TITLE
Change root within zip?

### ISSUE THREAD

**Issue by bartlewis** [sindresorhus/gulp-zip#3]
```
gulp.task('default', function () {
    gulp.src('src/*')
        .pipe(zip('archive.zip'))
        .pipe(gulp.dest('dist'));
});
```

The above results in the "src" folder being the top level within the zip file. How do I make the contents of "src" the top level of the zip instead?

**Comment by kaelteschutz** [comment]
For me on OSX it is impossible to create an archive without the parent folder in it:
```
var scormArchiveTask = function () {
  gulp.src('**', {cwd: 'public'})
  .pipe(zip('archive.zip'))
  .pipe(gulp.dest('./public'))
}
```

**Comment by WarenGonzaga** [comment]
Anything doesnt work! I've tried the code but unlucky to achieve.
