### ISSUE TITLE
The plugin dosen't work when used to zip a filename.docset

### ISSUE THREAD

**Issue by Minwe** [sindresorhus/gulp-zip#39]
I use it  to zip a folder, there is a folder named  `filename.docset` in this folder, it not works (do nothing).

For example, it's like https://github.com/exlee/d3-dash-gen `D3JS.docset`.

What's wrong?

**Comment by sindresorhus** [comment]
What does your gulpfile look like?

**Comment by Minwe** [comment]
Sorry, it's my mistake. Thanks.

```
├── README.md
├── dist
│   └── D3JS.docset
└── gulpfile.js
```

**Not Working**

```js
gulp.task('default', function() {
  return gulp.src('dist/*')
      .pipe(zip('test.zip'))
      .pipe(gulp.dest('./'));
});
```

**Working:**

```js
gulp.task('default', function() {
  return gulp.src('dist/**/*')
      .pipe(zip('test.zip'))
      .pipe(gulp.dest('./'));
});
```
