### ISSUE TITLE
gulp-zip includes the cwd in the zip

### ISSUE THREAD

**Issue by TheDutchCoder** [sindresorhus/gulp-zip#43]
It would be nice if the cwd wasn't included in the zip archive as the root folder, or is this a limitation of how zip works on a Mac?

I'm used to be able to add files from dir `/foo/bar/**/*` to an archive, set the cwd to `foo` and end up with `/bar/**/*` as the archive structure.

Right now gulp-zip takes the cwd as the root, so you'll always end up with `/foo/bar/**/*`inside the archive.

Any possible solution to that?

**Comment by artem-malko** [comment]
+1

**Comment by sindresorhus** [comment]
Change the `base` in gulp.src. This has been answered many times before.

**Comment by TheDutchCoder** [comment]
Changing the base has no effect for me, it will generate a root folder with the same name as the archive.

Is this a limitation of unzip on Mac?

**Comment by askmatey** [comment]
Same here, Linux.

Changing the base has no effect for me.

Does anybody know an solution?

**Comment by askmatey** [comment]
#60
