### ISSUE TITLE
Skips empty folders

### ISSUE THREAD

**Issue by rootty** [sindresorhus/gulp-zip#44]
Hello,

I have following folder structure:

* zip_test
 * folder1
   * test.txt
    * folder2
      * test.txt
 * _folder2_ //empty folder

```javascript
gulp.task('ziptest', function () {
    return gulp.src('zip_test/**')
        .pipe(ziptest('archive.zip'))
        .pipe(gulp.dest(''));
});
```
As a result I have archive.zip with all folders except _/folder2_

Test environment:
1) Windows 8.1
2) "gulp": "^3.8.10"
3) "gulp-zip": "^2.0.3"
4) node -v v0.12.0

**Comment by rootty** [comment]
Even if i put .gitignore file into folder2/, it skips it.

**Comment by sindresorhus** [comment]
`gulp.src` matches files. If you want a folder put a `dotfile` in it. You'll also need to pass in the option to `gulp.src` to enable matching dotfiles.

**Comment by rootty** [comment]
@sindresorhus interesting, if I just copying from src to dest, it also copying empty folders to new destination.
```javascript
gulp.task('ziptest', function () {
    return gulp.src('zip_test/**/*')
        .pipe(debug({title: 'unicorn:'}))
        //.pipe(ziptest('archive.zip'))
        .pipe(gulp.dest('zip_test2'));
});
```

Generally, thank you for an advice with .dot-files.

**Comment by sindresorhus** [comment]
Actually, yeah, I guess I could use https://stuk.github.io/jszip/documentation/api_jszip/folder_data.html for folders.

**Comment by dduponchel** [comment]
On `file(...)`, `dir : file.isDirectory()` will work too :) (see https://stuk.github.io/jszip/documentation/api_jszip/file_data.html)

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/gulp-zip/commit/1239836bbae8f0961776406e5f55072ebb51d1c8

Still needs a test. I don't have time to do that right now. So if you want it published, PR welcome for a test ;)
