### ISSUE TITLE
Error with zip

### ISSUE THREAD

**Issue by kidesigner** [sindresorhus/gulp-zip#47]
I have error with your example code:

node_modules/gulp-zip/node_modules/yazl/index.js:65
 entry.uncompressedSize = buffer.length;
                                 ^
TypeError: Cannot read property 'length' of null

**Comment by kevva** [comment]
Pretty sure this was related to https://github.com/sindresorhus/gulp-zip/pull/46.

**Comment by kidesigner** [comment]
Please help me.

**Comment by kevva** [comment]
Are you trying to compress any empty folders?

**Comment by kidesigner** [comment]
My project:
<pre>
css
js
node_modules
gulpfile.js
index.php
</pre>
and here is gulpfile content:
gulp.task('zip', function () {
    return gulp.src('css/*')
        .pipe(zip('archive.zip'))
        .pipe(gulp.dest('dist'));
});

**Comment by kevva** [comment]
Can you try installing this module directly from github (`npm install https://github.com/sindresorhus/gulp-zip/archive/master.tar.gz`) and try again?

**Comment by kidesigner** [comment]
Solve! It's working! thank you with your rocket support!

**Comment by kevva** [comment]
Sweet! :)

**Comment by jamesmorgan** [comment]
:+1: this would be good to get a fix out for :smile:
