### ISSUE TITLE
Zip file is rejected by Chrome webstore

### ISSUE THREAD

**Issue by volker48** [sindresorhus/gulp-zip#5]
Sorry I can't be more descriptive, but if you create a zip of a chrome extension folder with gulp-zip and try and upload it to the chrome webstore the server will reject the file with an error. http://i.imgur.com/dTqk6Kz.png. I also noticed that zipping the same folder from the OS X command line results in a file size that is about 1k larger than when zipping with gulp http://i.imgur.com/rvlCXsq.png. This is the only info I have from google {"errorMessage":{"reason":"REQUEST_REJECTED","additionalInfo":{"uploader_service.GoogleRupioAdditionalInfo":{"completionInfo":{"status":"REJECTED","customerSpecificInfo":{"extension_id":"null","errors":["Chrome Web Store system error, please try again later."],"upload_status":"FAILURE"}},"requestRejectedInfo":{"reasonDescription":"agent_rejected"}}},"upload_id":"redacted"}}

**Comment by redochka** [comment]
This is issue is back again :     "gulp-zip": "^4.1.0"
