### ISSUE TITLE
Unzipped file on unix has invalid permissions

### ISSUE THREAD

**Issue by santiagoaguiar** [sindresorhus/gulp-zip#51]
On windows, `fs.stat` of directory returns 040644, and since yazl mode option is set using this value when called from gulp-zip, the unzipped directory on linux cannot be accesed. 

For directories, it should use 040775 as yazl does or leave the decision to yazl itself.

**Comment by kevva** [comment]
Try installing this directly from GitHub and see if it resolves your issue.

**Comment by santiagoaguiar** [comment]
It does, thanks!

**Comment by kevva** [comment]
Sweet!
