### ISSUE TITLE
Zipping .htaccess file

### ISSUE THREAD

**Issue by pauldtyler** [sindresorhus/gulp-zip#59]
Great module. Thanks for doing this. For some reason, I can't get it to pull in a .htaccess file in the zipped bundle. have tried:

var Src = 'aws/*';
and 
var Src = 'aws/**/*.*';
----
gulp.task('aws_zip', function () {
  var Src = 'aws/*';
  var Dst = 'aws';

  return gulp.src(Src)
    .pipe(zip('aws_archive.zip'))
    .pipe(gulp.dest(Dst));
});

Any suggestions? Thanks.

**Comment by sindresorhus** [comment]
You have to use the `dot` option in `gulp.src` to get dotfiles:

> dot Include .dot files in normal matches and globstar matches. Note that an explicit dot in a portion of the pattern will always match dot files. - https://github.com/isaacs/node-glob

**Comment by jonathanasquier** [comment]
Hi, same usecase, won't work with dot option in gulp.src, or by specifying explicitly the dot folder/file in the gulp.src array (3.2.0)
```
gulp.task('zip', function(){
	return gulp.src([
		'build/**/*',
		'build/.hiddenfolder'
	],{dot : true})
	.pipe(zip('archive.zip'))
	.pipe(gulp.dest("somefolder"));
});
```

Any suggestions? Thanks.

**Comment by pauldtyler** [comment]
Suggestion from @sindresorhus worked for me. Currently using this to zip all files, including .htaccess:

gulp.task('aws_zip', function () {
  var Src = 'aws/**';
  var Dst = 'aws';

  return gulp.src([Src], {dot: true})
    .pipe(zip('aws_archive.zip'))
    .pipe(gulp.dest(Dst));
});

**Comment by jonathanasquier** [comment]
Works!
I thought I had tested everything...
