### ISSUE TITLE
Corrupted archives on Windows machines

### ISSUE THREAD

**Issue by patrykziem** [sindresorhus/gulp-zip#65]
After updating to latest version (3.1.0) archives created on windows machines (Confirmed on win8 and win10) are corrupted.

Works fine on OSX.

Version 3.0.2 was ok.

Edit: This is weird since they are not really corrupted. They appear as corrupted on both OSX and linux machines, but are fine on windows machines.

Archiving on windows prevents opening files on linux/OSX.
Archiving on OSX/Linux is fine.

This prevents deployment to services such as EBS, which require zip to be uploaded.

**Comment by mramato** [comment]
We are running into the same issue in [Cesium](https://github.com/AnalyticalGraphicsInc/cesium).  3.0.2 works as expected, but 3.10 changes permissions when archiving on Windows and unzipping on Linux.  I think this is related to (if not exactly the same as) #62 and #64.

Given #62 and #64 are closed, I hope that doesn't mean this isn't the standard behavior going forward.  I have to imagine that this use case is very typical and wants to be supported out of the box.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-zip/issues/64#issuecomment-192322345
