### ISSUE TITLE
zipped files decompress much larger than the original files

### ISSUE THREAD

**Issue by nalbion** [sindresorhus/gulp-zip#72]
There is a 105MB file within the `lambda-lib.zip` archive at [node-oracledb-for-lambda](https://github.com/nalbion/node-oracledb-for-lambda/tree/1.9.3-3).  When I use `gulp-zip` to add it to a new zip archive, and then unzip that archive the 105MB file has grown to **140MB**.

**Comment by sindresorhus** [comment]
Weird. Can you open this on https://github.com/thejoshwolfe/yazl which is the underlaying lib that handles the actual zipping.

**Comment by nalbion** [comment]
Done - https://github.com/thejoshwolfe/yazl/issues/25

**Comment by nalbion** [comment]
sorry - "user error"
