### ISSUE TITLE
Folder attribute

### ISSUE THREAD

**Issue by owianbarnett** [sindresorhus/gulp-zip#73]
I've been 7zipping a nodejs application package to load to AWS Lamda (simple js with node_modules including csv2json).

This works fine but I recently setup a gulp build using gulp-zip to manage the packaging for me.

On comparing the expanded zip contents using winmerge there are no differences.
Using 7Zip I can there are some differences.
1. Host is reported as FAT and the gulp-zip one is reported as Unix (ok?)
2. Attributes:
- the 7zip generated archive attributes is reported as simply D
- the gulp-zip generated archive attributes however, are reported as D drw-rw-rw-

I'm not sure if that's to be expected but it's the only difference I can find. 7Zip has no issue extracting the archive but whatever AWS Lamda uses to extract seems to fail to extract the archive folders.

Is this set of attributes correct combining the D and the drw-rw-rw?

**Comment by sindresorhus** [comment]
You'll probably have better luck asking on https://github.com/thejoshwolfe/yazl This module is just a thin wrapper around it.

**Comment by owianbarnett** [comment]
Thanks I'll do that.
