### ISSUE TITLE
Adobe PhoneGap Build

### ISSUE THREAD

**Issue by byronigoe** [sindresorhus/gulp-zip#74]
When I build a zip file with this plugin, PhoneGap Build is unable to properly read it (Windows can read it fine). A zip file built manually (with 7-Zip or Windows built-in) is read properly by PhoneGap Build. What is the difference?

The filesizes of the two zip files are a little different (1.6%), but that appears to be the only difference I can see.

**Comment by sindresorhus** [comment]
Can you open this on https://github.com/thejoshwolfe/yazl, which is the underlaying lib that handles the actual zipping, and post the link here.
