### ISSUE TITLE
EACCESS error on AWS after zipping on windows

### ISSUE THREAD

**Issue by JohnLErvin** [sindresorhus/gulp-zip#77]
Developing node app on windows, using gulp and gulp-zip 3.2.

The folders seem to have the wrong permissions on elastic beanstalk. I zip manually everything is fine. Read another issue that cloning from github instead of installing with npm is a workaround. That seems a bit unsatisfactory. 

Is there a way to configure around this? Is there an alternative zip package for gulp that does not suffer from this problem?

**Comment by SamVerschueren** [comment]
This should solve your issue https://github.com/sindresorhus/gulp-zip/issues/64#issuecomment-205324031.
