### ISSUE TITLE
Created archive does not work with lambda?

### ISSUE THREAD

**Issue by re-jim** [sindresorhus/gulp-zip#83]
I have this:

```
gulp.task('newInstanceSetup', function() {
    return gulp.src('./**/*',{cwd:'./new_instance_setup'})
        .pipe(zip('archive.zip'))
        .pipe(lambda(newInstanceSetup_params, opts))
        .pipe(gulp.dest('.'));
});
```

This causes errors when the code is executed by AWS Lambda.

If I manually zip the contents of the folder (select all > right click > 7-zip > add to archive...) it'll create an archive that works with Lambda.

If I manually upload the archive.zip created by the gulp process, Lambda will throw an error when executing the code. That leads me to believe that the error is somewhere in the gulp zipping process.

If I inspect both of the archives the filesize is different, but the contents look the same at first glance.

**Comment by re-jim** [comment]
Found the solution from #64 , add `nodir:true`

**Comment by deanshelton913** [comment]
`{nodir:true}` still leaves a parent directory in the zip
