### ISSUE TITLE
Cannot maintain folder structure when producing zip package for AWS deployments

### ISSUE THREAD

**Issue by lusocoding** [sindresorhus/gulp-zip#84]
When I try to produce a zip file for AWS deployments that has a '.ebextensions' folder inside, I cannot maintain the necessary structure. Either that folder is not included in the package, or I can include the files inside but not the tree structure.

#### Steps to reproduce
Please consider the following structure and gulp file
![image](https://cloud.githubusercontent.com/assets/114126/21806416/064bd614-d731-11e6-958e-00e01dbdfbf5.png)

```javascript
var gulp = require('gulp'),
    zip = require('gulp-zip');

gulp.task('zip', function () {
    return gulp.src([
            '*.js', 
            '.ebextensions/*'
        ])
        .pipe(zip('package_foo.zip'))
        .pipe(gulp.dest('packages'));
});
```

This will produce a package_foo.zip with the following contents:
![image](https://cloud.githubusercontent.com/assets/114126/21806451/46b8a1b4-d731-11e6-82e6-018c70b18e02.png)

On the other hand, if I try to change the zip task and include only the folder name:
```javascript
var gulp = require('gulp'),
    zip = require('gulp-zip');

gulp.task('zip', function () {
    return gulp.src([
            '*.js', 
            '.ebextensions'
        ])
        .pipe(zip('package_foo.zip'))
        .pipe(gulp.dest('packages'));
});
```

The package indeed has the '.ebextensionsfolder' inside but without any files.

**Comment by rorystandley** [comment]
This might just be a gulp.src issue - Try using the base like this -

`
gulp.task('zip', function () {
    return gulp.src([
            '*.js',
            '.ebextensions'
        ],
        {
            base: './'
        })
        .pipe(zip('package_foo.zip'))
        .pipe(gulp.dest('packages'));
});
`

**Comment by dillonsvincent** [comment]
` gulp.src(['framework/lambda_functions/test_controller/**/*', 'framework/api/API.Framework.js'],{ dot: true, nodir: true })
pipe(zip('archive.zip'))
.pipe(gulp.dest('dist/lambda/controller/archives'));`

First I had to use the dot: true to make sure it was picking up file names that start with a dot, such as .bin in the mode_modules. Second the /**/*, this will copy contents of the directories.

**Comment by lusocoding** [comment]
Hi @rorystandley, sorry for the late reply but your solution work indeed. Thanks 👍
