### ISSUE TITLE
FEATURE REQUEST: zip files recursively

### ISSUE THREAD

**Issue by operapreneur** [sindresorhus/gulp-zip#96]
Is it possible to have an option that recursively zips a directory?

For example, from the command line, you can run `zip -r`

Thanks!

**Comment by kevva** [comment]
It will zip the files that matches your glob. The following will add all files inside `src`:

```js
gulp.task('default', () =>
	gulp.src('src/**/*')
		.pipe(zip('archive.zip'))
		.pipe(gulp.dest('dist'))
);
```
