### ISSUE TITLE
Deprecation of Gulp-util

### ISSUE THREAD

**Issue by thedark1337** [sindresorhus/gulp-zip#99]
I've been using Gulp 4 alpha 2 fine with gulp-zip, but with the recent update to alpha 3, this module breaks due to using gulp-util to create files. There is also the usage of PluginError, with an alternative listed on the gulp-util repo.

[gulp-util](https://github.com/gulpjs/gulp-util) recommends using [vinyl](https://www.npmjs.com/package/vinyl) directly to create files and using [plugin-error](https://www.npmjs.com/package/plugin-error) directly to log errors. 

If possible, could you update gulp-zip for these changes?

**Comment by ivandotv** [comment]
@thedark1337 
I have made a [pull request](#100) regarding this issue.
